import Link from "next/link";

// Registry of all platform translations. When a new one is added under
// app/demos/<slug>, add an entry here so the landing page lists it. The SKILL
// instructs Claude to do this automatically whenever it generates a new
// translation.
const demos = [
  {
    slug: "servicenow-itsm-exemplar",
    platform: "ServiceNow",
    name: "ITSM Exemplar — Incidents",
    scenario:
      "L1 intake → assignment → resolution. Mock Table API for incident records plus matching UI.",
    status: "example" as const,
  },
  {
    slug: "sap-me5a-smoke",
    platform: "SAP",
    name: "ME5A — List Display of Purchase Requisitions",
    scenario:
      "SAP GUI procurement transaction with selection screen, ALV grid, status dots, and 6 seed PRs. Exercises the shared SAP chrome.",
    status: "smoke" as const,
  },
  {
    slug: "amazon-punchout-smoke",
    platform: "Amazon Business",
    name: "Punchout Storefront",
    scenario:
      "Storefront with punchout session banner, 6 business-catalog products, Add-to-Cart, and Submit-to-Elementum cart return. Exercises the shared Amazon chrome.",
    status: "smoke" as const,
  },
];

export default function Home() {
  return (
    <main className="mx-auto max-w-4xl px-6 py-12">
      <header className="mb-10">
        <h1 className="text-2xl font-semibold tracking-tight">
          Elementum Translator
        </h1>
        <p className="mt-2 text-sm text-neutral-600">
          Translates customer source-of-record platforms into grounded mock
          environments for SE demos. Every translation here is grounded in what
          the real platform can actually do — see{" "}
          <code className="rounded bg-neutral-100 px-1 py-0.5 text-xs">
            SKILL.md
          </code>{" "}
          and{" "}
          <code className="rounded bg-neutral-100 px-1 py-0.5 text-xs">
            PLATFORMS/
          </code>
          .
        </p>
      </header>

      <section>
        <h2 className="mb-3 text-sm font-medium uppercase tracking-wide text-neutral-500">
          Available translations
        </h2>
        <ul className="divide-y divide-neutral-200 rounded-lg border border-neutral-200 bg-white">
          {demos.map((d) => (
            <li key={d.slug}>
              <Link
                href={`/demos/${d.slug}`}
                className="flex items-start justify-between gap-6 px-5 py-4 hover:bg-neutral-50"
              >
                <div>
                  <div className="flex items-center gap-2">
                    <span className="rounded bg-neutral-900 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide text-white">
                      {d.platform}
                    </span>
                    {d.status === "example" && (
                      <span className="rounded border border-amber-300 bg-amber-50 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide text-amber-700">
                        example
                      </span>
                    )}
                    {d.status === "smoke" && (
                      <span className="rounded border border-sky-300 bg-sky-50 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide text-sky-700">
                        smoke
                      </span>
                    )}
                  </div>
                  <h3 className="mt-1.5 text-base font-medium text-neutral-900">
                    {d.name}
                  </h3>
                  <p className="mt-1 text-sm text-neutral-600">{d.scenario}</p>
                </div>
                <div className="pt-1 text-xs text-neutral-400">→</div>
              </Link>
            </li>
          ))}
        </ul>
      </section>

      <footer className="mt-12 border-t border-neutral-200 pt-6 text-xs text-neutral-500">
        Generated by the Elementum Translator skill. To add a new translation,
        open this repo in Cowork and ask Claude: <em>"build me a
        &lt;platform&gt; mock for my &lt;scenario&gt; demo."</em>
      </footer>
    </main>
  );
}
